# Generated by Django 4.2.2 on 2023-06-20 06:05

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('class_price', models.SmallIntegerField()),
                ('additional_price', models.SmallIntegerField()),
            ],
            bases=(models.Model, data.models.shows_name),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=(models.Model, data.models.shows_name),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('got_classes', models.SmallIntegerField()),
                ('left_classes', models.SmallIntegerField()),
                ('paid_money', models.SmallIntegerField()),
                ('required_money', models.SmallIntegerField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.class')),
            ],
            bases=(models.Model, data.models.shows_name),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.stage')),
            ],
            bases=(models.Model, data.models.shows_name),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.grade'),
        ),
    ]
